// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: invite.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO
    invites (
        user_id,
        experiment_id
    )
VALUES
    ($1, $2)
RETURNING id, created_at, user_id, experiment_id
`

type CreateInviteParams struct {
	UserID       uuid.UUID
	ExperimentID uuid.UUID
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRowContext(ctx, createInvite, arg.UserID, arg.ExperimentID)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.ExperimentID,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, created_at, user_id, experiment_id
FROM invites
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetInvite(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRowContext(ctx, getInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.ExperimentID,
	)
	return i, err
}

const getInvitesByExperimentId = `-- name: GetInvitesByExperimentId :many
SELECT id, created_at, user_id, experiment_id
FROM invites
WHERE experiment_id = $1
`

func (q *Queries) GetInvitesByExperimentId(ctx context.Context, experimentID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, getInvitesByExperimentId, experimentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.ExperimentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingInvites = `-- name: GetPendingInvites :many
SELECT id, created_at, user_id, experiment_id FROM invites WHERE invites.user_id = $1 AND invites.experiment_id NOT IN 
(SELECT experiment_id FROM experiment_results WHERE experiment_results.user_id = $1)
ORDER BY invites.created_at ASC
`

func (q *Queries) GetPendingInvites(ctx context.Context, userID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, getPendingInvites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.ExperimentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
