// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: schema.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Schema {
  public static partial class Backend
  {
    static readonly string __ServiceName = "schema.Backend";

    static readonly grpc::Marshaller<global::Schema.CounterRequest> __Marshaller_schema_CounterRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schema.CounterRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Schema.CounterResponse> __Marshaller_schema_CounterResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Schema.CounterResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Schema.CounterRequest, global::Schema.CounterResponse> __Method_Counter = new grpc::Method<global::Schema.CounterRequest, global::Schema.CounterResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "Counter",
        __Marshaller_schema_CounterRequest,
        __Marshaller_schema_CounterResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Schema.SchemaReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Backend</summary>
    [grpc::BindServiceMethod(typeof(Backend), "BindService")]
    public abstract partial class BackendBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Schema.CounterResponse> Counter(grpc::IAsyncStreamReader<global::Schema.CounterRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Backend</summary>
    public partial class BackendClient : grpc::ClientBase<BackendClient>
    {
      /// <summary>Creates a new client for Backend</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BackendClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Backend that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BackendClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BackendClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BackendClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncClientStreamingCall<global::Schema.CounterRequest, global::Schema.CounterResponse> Counter(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Counter(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Schema.CounterRequest, global::Schema.CounterResponse> Counter(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_Counter, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BackendClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BackendClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BackendBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Counter, serviceImpl.Counter).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, BackendBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Counter, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Schema.CounterRequest, global::Schema.CounterResponse>(serviceImpl.Counter));
    }

  }
}
#endregion
