name: CI

on:
  push:
    branches-ignore: [main]

jobs:
  go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vsn-backend
    steps:
      - uses: actions/checkout@v3

      - name: Go Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Go Build
        run: go build -v ./...

      - name: Go lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./vsn-backend

      - name: Go Test
        run: go test -v ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Super-Linter
        uses: github/super-linter@v4.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: ./**/*.(md|yaml|asset|obj|meta|txt|mtl|config|unity|twirp.*|pb.*|go)
